version: '3'
services:
  # myapplication:
  #   image: mongodb/mongodb-community-server:6.0-ubi8
  #   environment:
  #     - CONN_STR=mongodb://user:pass@mongodb
  #   command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
  #   depends_on:
  #     - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_OPULENS_USER=${MONGODB_OPULENS_USER}
      - MONGODB_OPULENS_PASSWORD=${MONGODB_OPULENS_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./init-mongo.js
        target: /docker-entrypoint-initdb.d/init-mongo.js
        read_only: true
      - type: bind
        source: ./mongodb/data
        target: /data/db
